Class = require("lib/hump.class")
Vector = require("lib/hump.vector")
Math = require("Class/Math")
Gamestate = require("lib/hump.gamestate")
require("GameStates/MainMenu")
require("GameStates/Game")
require("Class/Enemy")
require("Class/Player")
require("Class/Color")
require("Class/Settings")
require("Class/Bullet")
require("Class/BulletManager")

function love.load()
    Gamestate.registerEvents()
    print(MainMenu)
    Gamestate.switch(MainMenu)
end
